#!/bin/sh

if [ -f OMakefile ]; then
   if [ -t 1 ] ; then clear; fi
   omake $*
elif [ -f jbuild ]; then
   if [ -t 1 ] ; then clear; fi
   jbuilder $*   
else
   if [ -t 1 ] ; then clear; fi
   make $*
fi

